"""Application constants and magic numbers"""
from enum import Enum

class AlertType(Enum):
    KNOWN_PERSON = "nguoi_quen"
    STRANGER = "nguoi_la"
    FIRE_WARNING = "lua_chay_nghi_ngo"
    FIRE_CRITICAL = "lua_chay_khan_cap"

class ActionCode(Enum):
    TOGGLE_ON = "TOGGLE_ON"
    TOGGLE_OFF = "TOGGLE_OFF"
    GET_IMAGE = "GET_IMAGE"
    ALARM_ON = "ALARM_ON"
    ALARM_OFF = "ALARM_OFF"

# Detection thresholds
FACE_RECOGNITION_THRESHOLD = 0.4
FIRE_CONFIDENCE_THRESHOLD = 0.7
PERSON_CONFIDENCE_THRESHOLD = 0.6
IOU_THRESHOLD = 0.3

# Frame processing
FRAMES_REQUIRED_FOR_CONFIRMATION = 3
PROCESS_EVERY_N_FRAMES = 3
TARGET_FPS = 20
PROCESS_SIZE = (1280, 720)

# Tracking
TRACKER_TIMEOUT_SECONDS = 2.0
FACE_RECOGNITION_COOLDOWN = 1.0
STRANGER_CONFIRM_FRAMES = 25

# Fire detection
FIRE_WINDOW_SECONDS = 4
FIRE_YELLOW_ALERT_FRAMES = 5
FIRE_RED_ALERT_GROWTH_THRESHOLD = 1.5
FIRE_RED_ALERT_GROWTH_WINDOW = 7
FIRE_RED_ALERT_LOCKDOWN_SECONDS = 300

# Recording
RECORD_SECONDS = 10
STRANGER_CLIP_DURATION = 8
RECORDER_FPS = 20.0
RECORDER_FOURCC = "mp4v"

# Spam protection
DEBOUNCE_SECONDS = 30
SPAM_GUARD_MIN_INTERVAL = 10
SPAM_GUARD_MAX_PER_MINUTE = 4

# Telegram
USER_RESPONSE_WINDOW_SECONDS = 30
VIDEO_PREVIEW_LIMIT_MB = 48.0
HTTPX_TIMEOUT = 180

# Alarm
ALARM_FADE_IN_DURATION = 2
ALARM_START_VOLUME = 1.0
ALARM_MAX_VOLUME = 5.0

# AI
MAX_HISTORY_TURNS = 5
AI_MAX_TOKENS = 512
AI_TEMPERATURE = 0.5